name: App Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Switch directories
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.0'
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Run the tests
    - name: Run tests
      run: npm test
