name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Switch directory
      run: cd app
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.0'
    - name: Install dependencies
      run: cd app && npm ci
    - name: Build app
      run: cd app && npm run build --if-present
    - name: Run tests
      run: cd app && npm test
